name: flutter_plugin_qpos_example
description: Demonstrates how to use the flutter_plugin_qpos plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  progress_dialog: ^1.2.1
  cupertino_icons: ^1.0.0
  toast: ^0.1.3
  permission_handler: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_plugin_qpos:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - configs/emv_app.bin
    - configs/emv_capk.bin
    - configs/upgrader.asc
