name: flutter_plugin_qpos
description: A new Flutter plugin that development by Dspread.
version: 0.0.6

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  permission_handler: ^3.3.0
  meta: ^1.3.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.dspread.flutter_plugin_qpos
    pluginClass: FlutterPluginQposPlugin